spring:
  datasource:
    url: jdbc:mysql://124.223.77.164:3306/unicom?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: zs
    password: Zs123321,.
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-idle: 50
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-wait-millis: 60000
      time-between-eviction-runs-millis: 30000

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8
