server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    max-http-form-post-size: 104857600
    max-swallow-size: 104857600

logging.level:
  com.shopee.killer: info

spring:
  profiles:
    active: dev
  jmx:
    enabled: false
  session:
    timeout:
      seconds: 1800

mybatis:
  ##给实体类起别名
  type-aliases-package: com.shopee.killer.model
  ##引入mapper映射文件
  mapper-locations: classpath:mapper/*.xml